---
- name: "[LOCAL] Render Grafana root secrets"
  template:
    dest: "{{ __hs_grafana_root_var_file }}"
    src: "grafana.yml.j2"
    mode: 0600
  delegate_to: localhost
  become: false

- name: "[LOCAL] Encrypt Grafana root secrets if ANSIBLE_VAULT_PASSWORD_FILE"
  command: >-
    ansible-vault encrypt {{ __hs_grafana_root_var_file }}
  delegate_to: localhost
  become: false
  when:
    - __hs_ansible_vault_password_file_is_present

