---
- name: Restart nomad
  systemd:
    name: nomad
    state: restarted
    enabled: true
    daemon_reload: true

- name: Update ca trust
  command: >-
    {{ __hs_update_trust_command }}

- name: Reload kernel modules
  systemd:
    name: systemd-modules-load
    state: restarted
    enabled: true
