---
__hs_nomad_is_master: >-
  {{
    hs_nomad_inventory_masters_group is defined
    and hs_nomad_inventory_masters_group | length > 0
    and inventory_hostname in groups[hs_nomad_inventory_masters_group]
  }}
__hs_nomad_is_minion: "{{ not __hs_nomad_is_master }}"

__hs_nomad_is_mono_node: >-
  {{
    hs_nomad_inventory_masters_group is defined
    and hs_nomad_inventory_minions_group is defined
    and hs_nomad_inventory_masters_group | length > 0
    and hs_nomad_inventory_minions_group | length > 0
    and inventory_hostname in groups[hs_nomad_inventory_masters_group]
    and inventory_hostname in groups[hs_nomad_inventory_minions_group]
  }}

__hs_nomad_home_dir: "/opt/nomad"
__hs_nomad_data_dir: "{{ __hs_nomad_home_dir }}/data"

__hs_nomad_cni_plugins_dir: "/opt/cni/bin"

__hs_nomad_tls_dir: "/etc/ssl/private"
__hs_nomad_ssl_cert_group: "ssl-cert"

__hs_nomad_conf_dir: "/etc/nomad.d"
__hs_nomad_conf_file: "{{ __hs_nomad_conf_dir }}/nomad.hcl"
__hs_nomad_env_file: "{{ __hs_nomad_conf_dir }}/nomad.env"

__hs_nomad_self_private_key: "{{ __hs_nomad_tls_dir }}/self.cert.key"
__hs_nomad_self_certificate: "{{ __hs_nomad_tls_dir }}/self.fullchain.cert.pem"


__hs_nomad_ca_certificate: "{{ __hs_certs_truststore_dir }}/nomad.ca.crt"

__hs_nomad_vault_root_ca_certificate: "{{ __hs_certs_truststore_dir }}/vault.root_ca.crt"
__hs_nomad_encrypt_key_local_path: "{{ hs_nomad_local_secrets_dir }}/nomad.encrypt_key"
__hs_nomad_encrypt_key: >-
  {{ lookup('file', __hs_nomad_encrypt_key_local_path) }}

__hs_nomad_bootstrap_mark: 'hs_nomad_bootstrap'

__hs_nomad_api:
  acl_bootstrap: "{{ hs_nomad_address }}/v1/acl/bootstrap"
  status: "{{ hs_nomad_address }}/v1/status/leader"

__hs_nomad_vault_integration: >-
  {{
    hs_nomad_vault_address is defined
    and hs_nomad_vault_address | length > 4
    and hs_nomad_vault_token is defined
    and hs_nomad_vault_token | length > 4
  }}


__hs_nomad_archive_url: >-
  https://releases.hashicorp.com/nomad/{{ hs_nomad_version }}/nomad_{{ hs_nomad_version }}_linux_amd64.zip
__hs_nomad_archive_filename: "nomad_{{ hs_nomad_version }}_linux_amd64.zip"
__hs_nomad_local_archive_path: "{{ hs_local_cache_dir }}/{{ __hs_nomad_archive_filename }}"
__hs_nomad_license_file: "{{ __hs_nomad_conf_dir }}/nomad.license"

