---
- name: "Gather useful facts"
  setup:
    gather_subset:
      - "!hardware"
      - "!virtual"
      - "!ohai"
      - "!facter"

- name: "Load role vars"
  include_vars: "{{ _current_os_vars }}"
  with_first_found:
    - skip: true
      files: "{{ __hs_role_vars_precedence }}"
      paths: "{{ role_path }}/vars"
  loop_control:
    loop_var: _current_os_vars
  tags: always
