---
- name: "Gather vault version fact"
  import_tasks:
    file: "{{ role_path }}/tasks/__imports/__gather_vault_version_fact.yml"

- name: "Unarchive"
  unarchive:
    src: "{{ __hs_vault_local_archive_path }}"
    dest: "/usr/bin"
  when:
    - _hs_vault_version_current != hs_vault_version

- name: "Set permissions on vault binary"
  file:
    path: "/usr/bin/vault"
    owner: root
    group: vault
    mode: 0750

- name: "Render system service"
  template:
    src: "vault.service.j2"
    dest: "/lib/systemd/system/vault.service"
    mode: 0644
  notify: Restart vault
