---
- name: "Render prometheus service env"
  template:
    src: "default.env.j2"
    dest: "/etc/default/prometheus"
    mode: 0644
  notify: "Restart prometheus service"

- name: "Enable prometheus service"
  systemd:
    daemon_reload: true
    name: "prometheus"
    state: started
    enabled: true

