---
- name: "Prepare [{{ ansible_role_name }}]"
  include_tasks: _prepare.yml
  tags:
    - prepare
    - online

- name: "Install [{{ ansible_role_name }}]"
  include_tasks: _install.yml
  tags:
    - install

- name: "Configure [{{ ansible_role_name }}]"
  include_tasks: _configure.yml
  tags:
    - configure
