---
- name: Create Loki dir
  file:
    path: "/var/lib/loki"
    state: directory
    owner: loki
    group: loki
    mode: 0755

- name: "Render configuration"
  template:
    src: "loki.config.yml.j2"
    dest: "{{ __hs_loki_config_file }}"
    mode: 0644
  notify: "Restart loki service"

