---
- name: Prepare
  include_tasks: _prepare.yml
  tags:
    - prepare
    - online
    - loki

- name: Install Loki
  include_tasks: _install.yml
  when: inventory_hostname in groups['hashistack_sre']
  tags:
    - install
    - loki

- name: Configure
  include_tasks: _configure.yml
  when: inventory_hostname in groups['hashistack_sre']
  tags:
    - configure
    - loki

