---
# Implementation of:
# https://developer.hashicorp.com/vault/tutorials/standard-procedures/sop-backup
- name: "Load collection common vars"
  import_role:
    name: "vault_vars"
  tags:
    - always

- name: "Snapshot"
  shell:
    cmd: >-
      source {{ __hs_vault_snapshot_home_dir }}/.bash_profile &&
      vault operator raft snapshot save
      {{ __hs_vault_snapshot_home_dir }}/snapshots/vault.{{ ansible_date_time.iso8601_basic_short }}.snapshot
    executable: /usr/bin/bash
    chdir: "{{ __hs_vault_snapshot_home_dir }}/snapshots"

- name: "Create archive"
  shell:
    cmd: >-
      duplicity backup {{ __hs_vault_snapshot_home_dir }}/snapshots
      file://{{ __hs_vault_snapshot_home_dir }}
    executable: /usr/bin/bash
  environment:
    PASSPHRASE: "{{ hs_vault_snapshot_passphrase }}"

