---
- name: "Load collection common vars"
  import_role:
    name: "common_vars"
  tags:
    - always

- name: "Load role os vars"
  include_vars: "{{ _current_os_vars }}"
  with_first_found:
    - skip: true
      files: "{{ __hs_role_vars_precedence }}"
  loop_control:
    loop_var: _current_os_vars
  when:
    - ansible_distribution is defined
    - ansible_distribution | length > 0
  tags: always

- name: "Execute os tasks"
  include_tasks: "{{ _current_os_tasks }}"
  with_first_found:
    - skip: true
      files: "{{ __hs_role_tasks_precedence }}"
  loop_control:
    loop_var: _current_os_tasks
  tags: always

- name: "End-of-role flush"
  meta: flush_handlers
  tags: always
