---
- name: "Import rtnp.galaxie_clans playbook for letsencrypt management"
  import_playbook: rtnp.galaxie_clans.acme_rotate_certificates
  vars:
    scope: "hashistack_sre[0]"
    acme_nsupdate_key_secret: "{{ hs_dns_key_secret }}"
    acme_nsupdate_host: "{{ edge_public_ipv4 }}"
    acme_account_email: "hostmaster@{{ public_domain }}"

- name: Get generated certificate locally for distribution
  hosts: "hashistack_sre[0]"
  become: true
  gather_facts: false

  tasks:
    - name: "Load collection variables"
      import_role:
        name: "wescale.hashistack.common_vars"

    - name: Get certificate
      fetch:
        src: "/etc/ssl/private/*.{{ public_domain }}.{{ _current_part.extension }}"
        dest: "{{ _current_part.dest }}"
        flat: true
      loop:
        - extension: crt
          dest: "{{ hs_workspace_secrets_dir }}/self.cert.pem"
        - extension: "key"
          dest: "{{ hs_workspace_secrets_dir }}/self.cert.key"
        - extension: "fullchain.crt"
          dest: "{{ hs_workspace_secrets_dir }}/self.fullchain.cert.pem"
      loop_control:
        loop_var: _current_part
      tags:
        - fetch

