---
- name: "Stage 3 - Nomad prerequisites"
  hosts: "hashistack_cluster"
  become: true
  gather_facts: true

  tasks:
    - name: Install skopeo
      package:
        name: "skopeo"
        state: present

- name: "Stage 3 - Nomad installation"
  hosts: "hashistack_cluster"
  become: true
  gather_facts: true

  roles:
    - "rtnp.galaxie_clans.container"
    - "nomad"

