---
- name: "[VAULT] Snapshot"
  hosts: "hashistack_masters"
  become: true
  gather_facts: false

  tasks:
    - name: "Vault"
      include_role:
        name: "vault"
        tasks_from: "_inplace_init_unseal.yml"
        apply:
          tags:
            - vault
      tags:
        - vault


