---
- name: "[VAULT] Trust pki root"
  hosts: hashistack
  become: true
  gather_facts: true

  tasks:
    - name: "Vault"
      include_role:
        name: "vault"
        tasks_from: "__trust_pki_root.yml"
        apply:
          tags:
            - vault
      tags:
        - vault

