---
- name: "[VAULT] Snapshot"
  hosts: "hashistack_masters[0]"
  become: false
  gather_facts: true

  vars:
    ansible_ssh_user: "vault-snapshot"

  tasks:
    - name: "Vault"
      include_role:
        name: "vault"
        tasks_from: "__snapshot.yml"
        apply:
          tags:
            - vault
      tags:
        - vault

