---
- name: "[VAULT] Restore"
  hosts: "{{ scope | default('hashistack_masters') }}"
  become: false
  gather_facts: false

  vars:
    ansible_ssh_user: "vault-snapshot"

  tasks:
    - name: "Vault"
      include_role:
        name: "vault"
        tasks_from: "__restore.yml"
        apply:
          tags:
            - vault
      tags:
        - vault

