---
__hs_role_vars_precedence:
  - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}_{{ ansible_architecture | lower }}.yml"
  - "{{ ansible_distribution | lower }}_{{ ansible_architecture | lower }}.yml"
  - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_distribution | lower }}.yml"
  - "{{ ansible_os_family | lower }}.yml"

__hs_role_tasks_precedence:
  - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}_{{ ansible_architecture | lower }}/main.yml"
  - "{{ ansible_distribution | lower }}_{{ ansible_architecture | lower }}/main.yml"
  - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}/main.yml"
  - "{{ ansible_distribution | lower }}/main.yml"

__hs_ansible_vault_password_file_is_present: >-
  {{ (lookup('env', 'ANSIBLE_VAULT_PASSWORD_FILE') | length) > 0 }}

__hs_synchronize_rsync_opts: >-
  -e "ssh -F {{ hs_workspace_root }}/ssh.cfg"

