---
# __role_vars_precedence:
#   - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}_{{ ansible_architecture | lower }}.yml"
#   - "{{ ansible_distribution | lower }}_{{ ansible_architecture | lower }}.yml"
#   - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
#   - "{{ ansible_distribution | lower }}.yml"
#   - "{{ ansible_os_family | lower }}.yml"

# __role_tasks_precedence:
#   - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}_{{ ansible_architecture | lower }}/main.yml"
#   - "{{ ansible_distribution | lower }}_{{ ansible_architecture | lower }}/main.yml"
#   - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}/main.yml"
#   - "{{ ansible_distribution | lower }}/main.yml"
#
__hs_loki_host_is_minion: >-
  {{
    'hashistack_minions' in groups
    and inventory_hostname in groups['hashistack_minions']
  }}

