---
name: Build offline image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout project"
        uses: "actions/checkout@v4"
        with:
          repository: "${{ github.repository }}"
          path: "./"
      
      - name: "Build docker image"
        run: >-
          source .envrc &&
          make container-offline-installer
