---
name: linting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout project"
        uses: "actions/checkout@v3"
        with:
          repository: "${{ github.repository }}"
          path: "./"

      - name: "Install project dependencies"
        run: >-
          mkdir .direnv &&
          make prepare
        env:
          ANSIBLE_COLLECTIONS_PATH: "/home/runner/work/hashistack/hashistack/.direnv"
          ANSIBLE_ROLES_PATH: "/home/runner/work/hashistack/hashistack/roles"

      - name: "Lint"
        run: >-
          ansible-lint
        env:
          ANSIBLE_COLLECTIONS_PATH: "/home/runner/work/hashistack/hashistack/.direnv"
          ANSIBLE_ROLES_PATH: "/home/runner/work/hashistack/hashistack/roles"

