---
name: Stage1 Vault role workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vault_role:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout project"
        uses: "actions/checkout@v4"
        with:
          repository: "${{ github.repository }}"

      - name: "Install project dependencies"
        run: >-
          source .envrc &&
          make prepare

      - name: "Run molecule"
        run: >-
          cd ./roles/vault
          && molecule test
        env:
          ANSIBLE_FORCE_COLOR: "1"
